currentframe = 0
realCurrentFrame = 0
gridCellSize = 90
worldHeightCells = 11
worldHeightPx = worldHeightCells * gridCellSize
sideScrollSpeed = 10
sideScrollSpeed = 20
screenWidth = 1080
currentLevelWidth = 70